<a href="https://colab.research.google.com/github/sivakrushna-works/dl-with-pytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
t1 = torch.arange(10)

In [4]:
t2 = t1.reshape(2, 5)

In [5]:
t1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
t2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
t1[3] = 99

In [8]:
t1

tensor([ 0,  1,  2, 99,  4,  5,  6,  7,  8,  9])

In [9]:
t2

tensor([[ 0,  1,  2, 99,  4],
        [ 5,  6,  7,  8,  9]])

In [11]:
t3 = t1.reshape(5, 2)

In [12]:
t3

tensor([[ 0,  1],
        [ 2, 99],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]])

In [13]:
t1[5] = 19

In [14]:
t1

tensor([ 0,  1,  2, 99,  4, 19,  6,  7,  8,  9])

In [15]:
t2

tensor([[ 0,  1,  2, 99,  4],
        [19,  6,  7,  8,  9]])

In [16]:
t3

tensor([[ 0,  1],
        [ 2, 99],
        [ 4, 19],
        [ 6,  7],
        [ 8,  9]])

In [17]:
t3[3,1] = 15

In [18]:
t3

tensor([[ 0,  1],
        [ 2, 99],
        [ 4, 19],
        [ 6, 15],
        [ 8,  9]])

In [19]:
t2

tensor([[ 0,  1,  2, 99,  4],
        [19,  6, 15,  8,  9]])

In [20]:
t1

tensor([ 0,  1,  2, 99,  4, 19,  6, 15,  8,  9])

In [21]:
t4 = t1

In [22]:
t4

tensor([ 0,  1,  2, 99,  4, 19,  6, 15,  8,  9])

In [23]:
t5 = t1.clone()

In [24]:
t3[3,1] = 159

In [29]:
t5

tensor([ 0,  1,  2, 99,  4, 19,  6, 15,  8,  9])