<a href="https://colab.research.google.com/github/sivakrushna-works/dl-with-pytorch/blob/main/Tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [4]:
#add
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
#sub
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [7]:
#multiplication
tensor_a * tensor_b


tensor([ 5, 12, 21, 32])

In [8]:
#division
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [9]:
#power
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [10]:
#module
tensor_a % tensor_b

tensor([1, 2, 3, 4])

In [11]:
#reassigning the output with _
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [12]:
tensor_a

tensor([ 6,  8, 10, 12])